### ISSUE TITLE
Broken link for the full formalization

### ISSUE THREAD

**Issue by xvw** [CatalaLang/catala-website#10]
Hi, on the page: https://catala-lang.org/en/formalisation, the button "access the complete formalization pdf", point to https://github.com/CatalaLang/catala/raw/master/doc/formalization/formalization.pdf that is a dead-link. 

Cheers.

**Comment by denismerigoux** [comment]
Indeed, the correct link should be https://arxiv.org/abs/2103.03198. Will fix that!
