### ISSUE TITLE
Feat: improve rendering time of big Catala code examples

### ISSUE THREAD

**Issue by EmileRolley** [CatalaLang/catala-website#33]
The rendering of the [french housing example page](https://catala-lang.org/en/examples/housing-benefits) takes a significant amount of time compared to other pages.

Is there a way to optmize this?

**Comment by denismerigoux** [comment]
I guess you could make `<h2>`, `<h3>` sections collapsible so that they're rendered only when you click on them?

**Comment by EmileRolley** [comment]
Closed by https://github.com/CatalaLang/catala/pull/303
