### ISSUE TITLE
Problème d’affichage sur iOS

### ISSUE THREAD

**Issue by mquandalle** [CatalaLang/catala-website#7]
Sur un ipad : 

![79AACD15-4EA4-4638-B581-7EAADD28BA05](https://user-images.githubusercontent.com/1730702/105346841-603abd00-5be6-11eb-8b5a-50e0391cbc80.png)

**Comment by denismerigoux** [comment]
Salut ! Merci pour le bug report :) 

Je fais de mon mieux pour tester le site sur Firefox + Chrome y compris en responsive design et ça scale pas trop mal (même si c'est améliorable). Je sais pas pourquoi ça marche pas sur Safari + iPad... N'étant pas développeur web, je n'ai pas le temps ni la motivation de mettre en place un CI de l'espace qui teste 20 configs différentes. Malheureusement, le Web étant ce qu'il est, cette issue là sera won't fix pour moi...

J'update les packages node de temps en temps quand même, et ça m'a plutôt l'air de venir du framework CSS que j'utilise (TailwindCSS).

**Comment by danielleberre** [comment]
On observe le même problème sur safari sur macOS. Ce n'est pas limité aux iPad.
